/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ArenaIndexRouteImport } from './routes/arena/index'
import { Route as ConquestIndexRouteImport } from './routes/conquest/index'
import { Route as ConquestBossRouteImport } from './routes/conquest/boss'
import { Route as ConquestDecksRouteImport } from './routes/conquest/decks'
import { Route as ConquestGearRouteImport } from './routes/conquest/gear'
import { Route as ConquestMechanicsRouteImport } from './routes/conquest/mechanics'
import { Route as ConquestRunesRouteImport } from './routes/conquest/runes'
import { Route as ConquestScoresRouteImport } from './routes/conquest/scores'
import { Route as ConquestTimelineRouteImport } from './routes/conquest/timeline'
import { Route as RumbleIndexRouteImport } from './routes/rumble/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestIndexRoute = ConquestIndexRouteImport.update({
  id: '/conquest/',
  path: '/conquest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestBossRoute = ConquestBossRouteImport.update({
  id: '/conquest/boss',
  path: '/conquest/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestDecksRoute = ConquestDecksRouteImport.update({
  id: '/conquest/decks',
  path: '/conquest/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestGearRoute = ConquestGearRouteImport.update({
  id: '/conquest/gear',
  path: '/conquest/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestMechanicsRoute = ConquestMechanicsRouteImport.update({
  id: '/conquest/mechanics',
  path: '/conquest/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestRunesRoute = ConquestRunesRouteImport.update({
  id: '/conquest/runes',
  path: '/conquest/runes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestScoresRoute = ConquestScoresRouteImport.update({
  id: '/conquest/scores',
  path: '/conquest/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestTimelineRoute = ConquestTimelineRouteImport.update({
  id: '/conquest/timeline',
  path: '/conquest/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RumbleIndexRoute = RumbleIndexRouteImport.update({
  id: '/rumble/',
  path: '/rumble/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/conquest/boss': typeof ConquestBossRoute
  '/conquest/decks': typeof ConquestDecksRoute
  '/conquest/gear': typeof ConquestGearRoute
  '/conquest/mechanics': typeof ConquestMechanicsRoute
  '/conquest/runes': typeof ConquestRunesRoute
  '/conquest/scores': typeof ConquestScoresRoute
  '/conquest/timeline': typeof ConquestTimelineRoute
  '/arena/': typeof ArenaIndexRoute
  '/conquest/': typeof ConquestIndexRoute
  '/rumble/': typeof RumbleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/conquest/boss': typeof ConquestBossRoute
  '/conquest/decks': typeof ConquestDecksRoute
  '/conquest/gear': typeof ConquestGearRoute
  '/conquest/mechanics': typeof ConquestMechanicsRoute
  '/conquest/runes': typeof ConquestRunesRoute
  '/conquest/scores': typeof ConquestScoresRoute
  '/conquest/timeline': typeof ConquestTimelineRoute
  '/arena': typeof ArenaIndexRoute
  '/conquest': typeof ConquestIndexRoute
  '/rumble': typeof RumbleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/conquest/boss': typeof ConquestBossRoute
  '/conquest/decks': typeof ConquestDecksRoute
  '/conquest/gear': typeof ConquestGearRoute
  '/conquest/mechanics': typeof ConquestMechanicsRoute
  '/conquest/runes': typeof ConquestRunesRoute
  '/conquest/scores': typeof ConquestScoresRoute
  '/conquest/timeline': typeof ConquestTimelineRoute
  '/arena/': typeof ArenaIndexRoute
  '/conquest/': typeof ConquestIndexRoute
  '/rumble/': typeof RumbleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/sources'
    | '/conquest/boss'
    | '/conquest/decks'
    | '/conquest/gear'
    | '/conquest/mechanics'
    | '/conquest/runes'
    | '/conquest/scores'
    | '/conquest/timeline'
    | '/arena/'
    | '/conquest/'
    | '/rumble/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/sources'
    | '/conquest/boss'
    | '/conquest/decks'
    | '/conquest/gear'
    | '/conquest/mechanics'
    | '/conquest/runes'
    | '/conquest/scores'
    | '/conquest/timeline'
    | '/arena'
    | '/conquest'
    | '/rumble'
  id:
    | '__root__'
    | '/'
    | '/glossary'
    | '/sources'
    | '/conquest/boss'
    | '/conquest/decks'
    | '/conquest/gear'
    | '/conquest/mechanics'
    | '/conquest/runes'
    | '/conquest/scores'
    | '/conquest/timeline'
    | '/arena/'
    | '/conquest/'
    | '/rumble/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossaryRoute: typeof GlossaryRoute
  SourcesRoute: typeof SourcesRoute
  ConquestBossRoute: typeof ConquestBossRoute
  ConquestDecksRoute: typeof ConquestDecksRoute
  ConquestGearRoute: typeof ConquestGearRoute
  ConquestMechanicsRoute: typeof ConquestMechanicsRoute
  ConquestRunesRoute: typeof ConquestRunesRoute
  ConquestScoresRoute: typeof ConquestScoresRoute
  ConquestTimelineRoute: typeof ConquestTimelineRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
  ConquestIndexRoute: typeof ConquestIndexRoute
  RumbleIndexRoute: typeof RumbleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/': {
      id: '/arena/'
      path: '/arena'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/': {
      id: '/conquest/'
      path: '/conquest'
      fullPath: '/conquest/'
      preLoaderRoute: typeof ConquestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/boss': {
      id: '/conquest/boss'
      path: '/conquest/boss'
      fullPath: '/conquest/boss'
      preLoaderRoute: typeof ConquestBossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/decks': {
      id: '/conquest/decks'
      path: '/conquest/decks'
      fullPath: '/conquest/decks'
      preLoaderRoute: typeof ConquestDecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/gear': {
      id: '/conquest/gear'
      path: '/conquest/gear'
      fullPath: '/conquest/gear'
      preLoaderRoute: typeof ConquestGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/mechanics': {
      id: '/conquest/mechanics'
      path: '/conquest/mechanics'
      fullPath: '/conquest/mechanics'
      preLoaderRoute: typeof ConquestMechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/runes': {
      id: '/conquest/runes'
      path: '/conquest/runes'
      fullPath: '/conquest/runes'
      preLoaderRoute: typeof ConquestRunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/scores': {
      id: '/conquest/scores'
      path: '/conquest/scores'
      fullPath: '/conquest/scores'
      preLoaderRoute: typeof ConquestScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest/timeline': {
      id: '/conquest/timeline'
      path: '/conquest/timeline'
      fullPath: '/conquest/timeline'
      preLoaderRoute: typeof ConquestTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rumble/': {
      id: '/rumble/'
      path: '/rumble'
      fullPath: '/rumble/'
      preLoaderRoute: typeof RumbleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossaryRoute: GlossaryRoute,
  SourcesRoute: SourcesRoute,
  ConquestBossRoute: ConquestBossRoute,
  ConquestDecksRoute: ConquestDecksRoute,
  ConquestGearRoute: ConquestGearRoute,
  ConquestMechanicsRoute: ConquestMechanicsRoute,
  ConquestRunesRoute: ConquestRunesRoute,
  ConquestScoresRoute: ConquestScoresRoute,
  ConquestTimelineRoute: ConquestTimelineRoute,
  ArenaIndexRoute: ArenaIndexRoute,
  ConquestIndexRoute: ConquestIndexRoute,
  RumbleIndexRoute: RumbleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
