/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeRouteImport } from './routes/$mode'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ModeIndexRouteImport } from './routes/$mode/index'
import { Route as ModeBossRouteImport } from './routes/$mode/boss'
import { Route as ModeCountersRouteImport } from './routes/$mode/counters'
import { Route as ModeDecksRouteImport } from './routes/$mode/decks'
import { Route as ModeGearRouteImport } from './routes/$mode/gear'
import { Route as ModeMechanicsRouteImport } from './routes/$mode/mechanics'
import { Route as ModeRunesRouteImport } from './routes/$mode/runes'
import { Route as ModeScoresRouteImport } from './routes/$mode/scores'
import { Route as ModeTeamsRouteImport } from './routes/$mode/teams'
import { Route as ModeTimelineRouteImport } from './routes/$mode/timeline'
import { Route as ModeUsageRouteImport } from './routes/$mode/usage'
import { Route as ResearchSlugCapturesRouteImport } from './routes/research_.$slug.captures'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeIndexRoute = ModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeRoute,
} as any)
const ModeBossRoute = ModeBossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => ModeRoute,
} as any)
const ModeCountersRoute = ModeCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => ModeRoute,
} as any)
const ModeDecksRoute = ModeDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => ModeRoute,
} as any)
const ModeGearRoute = ModeGearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => ModeRoute,
} as any)
const ModeMechanicsRoute = ModeMechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => ModeRoute,
} as any)
const ModeRunesRoute = ModeRunesRouteImport.update({
  id: '/runes',
  path: '/runes',
  getParentRoute: () => ModeRoute,
} as any)
const ModeScoresRoute = ModeScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => ModeRoute,
} as any)
const ModeTeamsRoute = ModeTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ModeRoute,
} as any)
const ModeTimelineRoute = ModeTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ModeRoute,
} as any)
const ModeUsageRoute = ModeUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ModeRoute,
} as any)
const ResearchSlugCapturesRoute = ResearchSlugCapturesRouteImport.update({
  id: '/research_/$slug/captures',
  path: '/research/$slug/captures',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteWithChildren
  '/glossary': typeof GlossaryRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/$mode/boss': typeof ModeBossRoute
  '/$mode/counters': typeof ModeCountersRoute
  '/$mode/decks': typeof ModeDecksRoute
  '/$mode/gear': typeof ModeGearRoute
  '/$mode/mechanics': typeof ModeMechanicsRoute
  '/$mode/runes': typeof ModeRunesRoute
  '/$mode/scores': typeof ModeScoresRoute
  '/$mode/teams': typeof ModeTeamsRoute
  '/$mode/timeline': typeof ModeTimelineRoute
  '/$mode/usage': typeof ModeUsageRoute
  '/$mode/': typeof ModeIndexRoute
  '/research/$slug/captures': typeof ResearchSlugCapturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/$mode/boss': typeof ModeBossRoute
  '/$mode/counters': typeof ModeCountersRoute
  '/$mode/decks': typeof ModeDecksRoute
  '/$mode/gear': typeof ModeGearRoute
  '/$mode/mechanics': typeof ModeMechanicsRoute
  '/$mode/runes': typeof ModeRunesRoute
  '/$mode/scores': typeof ModeScoresRoute
  '/$mode/teams': typeof ModeTeamsRoute
  '/$mode/timeline': typeof ModeTimelineRoute
  '/$mode/usage': typeof ModeUsageRoute
  '/$mode': typeof ModeIndexRoute
  '/research/$slug/captures': typeof ResearchSlugCapturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteWithChildren
  '/glossary': typeof GlossaryRoute
  '/research': typeof ResearchRoute
  '/sources': typeof SourcesRoute
  '/$mode/boss': typeof ModeBossRoute
  '/$mode/counters': typeof ModeCountersRoute
  '/$mode/decks': typeof ModeDecksRoute
  '/$mode/gear': typeof ModeGearRoute
  '/$mode/mechanics': typeof ModeMechanicsRoute
  '/$mode/runes': typeof ModeRunesRoute
  '/$mode/scores': typeof ModeScoresRoute
  '/$mode/teams': typeof ModeTeamsRoute
  '/$mode/timeline': typeof ModeTimelineRoute
  '/$mode/usage': typeof ModeUsageRoute
  '/$mode/': typeof ModeIndexRoute
  '/research_/$slug/captures': typeof ResearchSlugCapturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$mode'
    | '/glossary'
    | '/research'
    | '/sources'
    | '/$mode/boss'
    | '/$mode/counters'
    | '/$mode/decks'
    | '/$mode/gear'
    | '/$mode/mechanics'
    | '/$mode/runes'
    | '/$mode/scores'
    | '/$mode/teams'
    | '/$mode/timeline'
    | '/$mode/usage'
    | '/$mode/'
    | '/research/$slug/captures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/research'
    | '/sources'
    | '/$mode/boss'
    | '/$mode/counters'
    | '/$mode/decks'
    | '/$mode/gear'
    | '/$mode/mechanics'
    | '/$mode/runes'
    | '/$mode/scores'
    | '/$mode/teams'
    | '/$mode/timeline'
    | '/$mode/usage'
    | '/$mode'
    | '/research/$slug/captures'
  id:
    | '__root__'
    | '/'
    | '/$mode'
    | '/glossary'
    | '/research'
    | '/sources'
    | '/$mode/boss'
    | '/$mode/counters'
    | '/$mode/decks'
    | '/$mode/gear'
    | '/$mode/mechanics'
    | '/$mode/runes'
    | '/$mode/scores'
    | '/$mode/teams'
    | '/$mode/timeline'
    | '/$mode/usage'
    | '/$mode/'
    | '/research_/$slug/captures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModeRoute: typeof ModeRouteWithChildren
  GlossaryRoute: typeof GlossaryRoute
  ResearchRoute: typeof ResearchRoute
  SourcesRoute: typeof SourcesRoute
  ResearchSlugCapturesRoute: typeof ResearchSlugCapturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode': {
      id: '/$mode'
      path: '/$mode'
      fullPath: '/$mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode/': {
      id: '/$mode/'
      path: '/'
      fullPath: '/$mode/'
      preLoaderRoute: typeof ModeIndexRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/boss': {
      id: '/$mode/boss'
      path: '/boss'
      fullPath: '/$mode/boss'
      preLoaderRoute: typeof ModeBossRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/counters': {
      id: '/$mode/counters'
      path: '/counters'
      fullPath: '/$mode/counters'
      preLoaderRoute: typeof ModeCountersRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/decks': {
      id: '/$mode/decks'
      path: '/decks'
      fullPath: '/$mode/decks'
      preLoaderRoute: typeof ModeDecksRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/gear': {
      id: '/$mode/gear'
      path: '/gear'
      fullPath: '/$mode/gear'
      preLoaderRoute: typeof ModeGearRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/mechanics': {
      id: '/$mode/mechanics'
      path: '/mechanics'
      fullPath: '/$mode/mechanics'
      preLoaderRoute: typeof ModeMechanicsRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/runes': {
      id: '/$mode/runes'
      path: '/runes'
      fullPath: '/$mode/runes'
      preLoaderRoute: typeof ModeRunesRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/scores': {
      id: '/$mode/scores'
      path: '/scores'
      fullPath: '/$mode/scores'
      preLoaderRoute: typeof ModeScoresRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/teams': {
      id: '/$mode/teams'
      path: '/teams'
      fullPath: '/$mode/teams'
      preLoaderRoute: typeof ModeTeamsRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/timeline': {
      id: '/$mode/timeline'
      path: '/timeline'
      fullPath: '/$mode/timeline'
      preLoaderRoute: typeof ModeTimelineRouteImport
      parentRoute: typeof ModeRoute
    }
    '/$mode/usage': {
      id: '/$mode/usage'
      path: '/usage'
      fullPath: '/$mode/usage'
      preLoaderRoute: typeof ModeUsageRouteImport
      parentRoute: typeof ModeRoute
    }
    '/research_/$slug/captures': {
      id: '/research_/$slug/captures'
      path: '/research/$slug/captures'
      fullPath: '/research/$slug/captures'
      preLoaderRoute: typeof ResearchSlugCapturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ModeRouteChildren {
  ModeBossRoute: typeof ModeBossRoute
  ModeCountersRoute: typeof ModeCountersRoute
  ModeDecksRoute: typeof ModeDecksRoute
  ModeGearRoute: typeof ModeGearRoute
  ModeMechanicsRoute: typeof ModeMechanicsRoute
  ModeRunesRoute: typeof ModeRunesRoute
  ModeScoresRoute: typeof ModeScoresRoute
  ModeTeamsRoute: typeof ModeTeamsRoute
  ModeTimelineRoute: typeof ModeTimelineRoute
  ModeUsageRoute: typeof ModeUsageRoute
  ModeIndexRoute: typeof ModeIndexRoute
}

const ModeRouteChildren: ModeRouteChildren = {
  ModeBossRoute: ModeBossRoute,
  ModeCountersRoute: ModeCountersRoute,
  ModeDecksRoute: ModeDecksRoute,
  ModeGearRoute: ModeGearRoute,
  ModeMechanicsRoute: ModeMechanicsRoute,
  ModeRunesRoute: ModeRunesRoute,
  ModeScoresRoute: ModeScoresRoute,
  ModeTeamsRoute: ModeTeamsRoute,
  ModeTimelineRoute: ModeTimelineRoute,
  ModeUsageRoute: ModeUsageRoute,
  ModeIndexRoute: ModeIndexRoute,
}

const ModeRouteWithChildren = ModeRoute._addFileChildren(ModeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModeRoute: ModeRouteWithChildren,
  GlossaryRoute: GlossaryRoute,
  ResearchRoute: ResearchRoute,
  SourcesRoute: SourcesRoute,
  ResearchSlugCapturesRoute: ResearchSlugCapturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
